version: 2.1

orbs:
  node: circleci/node@4.8.1

executors:
  default:
    docker:
      - image: cimg/node:14.17.4
    working_directory: ~/mobile-app

commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/mobile-app

jobs:
  install_deps:
    executor: default
    steps:
      - checkout
      - attach_project
      - run:
          name: Install Dependencies
          command: yarn install
      - persist_to_workspace:
          paths: ./*
          root: .
  eas_build:
    executor: default
    parameters:
      config:
        description: Build Config
        type: string
    steps:
      - checkout
      - attach_project
      - when:
          condition:
            equal: [<< parameters.config >>, "dev"]
          steps:
            - run:
                name: Dev Build
                command: EXPO_TOKEN="DCYHBgH7WSFkXvSCZCgiy7fNQEpXr2K9800sfEzu" npx eas-cli build --platform android --profile << parameters.config >> --non-interactive --no-wait
      - when:
          condition:
            not:
              equal: [<< parameters.config >>, "dev"]
          steps:
            - run:
                name: Prod Build
                command: EXPO_TOKEN="DCYHBgH7WSFkXvSCZCgiy7fNQEpXr2K9800sfEzu" npx eas-cli build --platform android --profile << parameters.config >> --non-interactive --no-wait
workflows:
  build_app:
    jobs:
      - install_deps
      - eas_build:
          name: Build Dev
          config: development
          filters:
            branches:
              only: develop
      - eas_build:
          name: Build Red Prod
          config: red
          filters:
            branches:
              only: master
      - eas_build:
          name: Build Blue Prod
          config: blue
          filters:
            branches:
              only: master
